# Generated by Django 4.1.12 on 2024-02-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
    ]
