# Generated by Django 4.1.12 on 2024-03-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
